-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: other.proto

module Other exposing (..)

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias Other =
    { stringField : String -- 1
    }


otherDecoder : JD.Decoder Other
otherDecoder =
    JD.lazy <| \_ -> Other
        <$> (requiredFieldDecoder "stringField" "" JD.string)


otherEncoder : Other -> JE.Value
otherEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "stringField" JE.string "" v.stringField)
        ]
