#!/bin/bash

set -ex

echo "Install libsysconfcpus to compensate for slow elm builds"
# More at: https://github.com/elm/compiler/issues/1473
if [ ! -d sysconfcpus/bin ]; then
    git clone https://github.com/obmarg/libsysconfcpus.git
    cd libsysconfcpus
    ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus
    make && make install
    cd ..
fi
