#!/bin/bash

set -x

# Make sure the current commit is tagged, using the following command:
# git tag -a 0.0.2 -m 'release'

TAG=$(git tag --contains)
[[ -z $TAG ]] && exit

OUT=elm-protobuf-${TAG}-linux-x86_32
GOOS=linux GOARCH=386 go build -o ./bin/${OUT}/protoc-gen-elm ./protoc-gen-elm
tar -zcvf ./bin/${OUT}.tar.gz ./bin/${OUT}

OUT=elm-protobuf-${TAG}-linux-x86_64
GOOS=linux GOARCH=amd64 go build -o ./bin/${OUT}/protoc-gen-elm ./protoc-gen-elm
tar -zcvf ./bin/${OUT}.tar.gz ./bin/${OUT}

OUT=elm-protobuf-${TAG}-osx-x86_32
GOOS=darwin GOARCH=386 go build -o ./bin/${OUT}/protoc-gen-elm ./protoc-gen-elm
tar -zcvf ./bin/${OUT}.tar.gz ./bin/${OUT}

OUT=elm-protobuf-${TAG}-osx-x86_64
GOOS=darwin GOARCH=amd64 go build -o ./bin/${OUT}/protoc-gen-elm ./protoc-gen-elm
tar -zcvf ./bin/${OUT}.tar.gz ./bin/${OUT}
