#!/bin/bash

set -x

TAG=$(git tag)

OUT=elm-protobuf-${TAG}-linux-x86_32
GOOS=linux GOARCH=386 go build -o ./bin/${OUT}/protoc-gen-elm ./protoc-gen-elm
tar -zcvf ./bin/${OUT}.tar.gz ./bin/${OUT}

OUT=elm-protobuf-${TAG}-linux-x86_64
GOOS=linux GOARCH=amd64 go build -o ./bin/${OUT}/protoc-gen-elm ./protoc-gen-elm
tar -zcvf ./bin/${OUT}.tar.gz ./bin/${OUT}

OUT=elm-protobuf-${TAG}-osx-x86_32
GOOS=darwin GOARCH=386 go build -o ./bin/${OUT}/protoc-gen-elm ./protoc-gen-elm
tar -zcvf ./bin/${OUT}.tar.gz ./bin/${OUT}

OUT=elm-protobuf-${TAG}-osx-x86_64
GOOS=darwin GOARCH=amd64 go build -o ./bin/${OUT}/protoc-gen-elm ./protoc-gen-elm
tar -zcvf ./bin/${OUT}.tar.gz ./bin/${OUT}
