#!/bin/bash

set -x

readonly BIN=protoc-gen-elm

# Make sure the current commit is tagged, using the following command:
# git tag -a v0.0.2 -m 'release'

# Remove the leading "v" from the tag, if necessary.
VERSION=$(git tag --contains | tr -d v)

# Exit if a tag does not exist for the current commit.
[[ -z $VERSION ]] && exit

OUT=elm-protobuf-${VERSION}-linux-x86_32
GOOS=linux GOARCH=386 go build -o ./bin/${OUT}/${BIN} ./${BIN}
tar -zcvf ./bin/${OUT}.tar.gz ./bin/${OUT}

OUT=elm-protobuf-${VERSION}-linux-x86_64
GOOS=linux GOARCH=amd64 go build -o ./bin/${OUT}/${BIN} ./${BIN}
tar -zcvf ./bin/${OUT}.tar.gz ./bin/${OUT}

OUT=elm-protobuf-${VERSION}-osx-x86_32
GOOS=darwin GOARCH=386 go build -o ./bin/${OUT}/${BIN} ./${BIN}
tar -zcvf ./bin/${OUT}.tar.gz ./bin/${OUT}

OUT=elm-protobuf-${VERSION}-osx-x86_64
GOOS=darwin GOARCH=amd64 go build -o ./bin/${OUT}/${BIN} ./${BIN}
tar -zcvf ./bin/${OUT}.tar.gz ./bin/${OUT}
