#!/bin/sh

set -ex

cd protoc-gen-elm
GO111MODULE=on go build -o ../bin ./cmd/protoc-gen-elm
cd ..

protoc \
    --proto_path=./tests/proto \
    --elm_out=./tests \
    --plugin=protoc-gen-elm=./bin/protoc-gen-elm \
    ./tests/proto/*.proto

elm-test 
