#!/bin/sh

set -ex

pushd protoc-gen-elm
go build .
popd

protoc \
    --proto_path=./tests/proto \
    --elm_out=./tests \
    --plugin=protoc-gen-elm=./protoc-gen-elm/protoc-gen-elm \
    ./tests/proto/*.proto

elm-test
