#!/bin/sh

set -ex

cd protoc-gen-elm
GO111MODULE=on go build .
cd ..

protoc \
    --proto_path=./tests/proto \
    --elm_out=./tests \
    --plugin=protoc-gen-elm=./protoc-gen-elm/protoc-gen-elm \
    ./tests/proto/*.proto

elm-test
