package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"protoc-gen-elm/elm"
	"strings"
	"text/template"

	"github.com/golang/protobuf/proto"
	plugin "github.com/golang/protobuf/protoc-gen-go/plugin"
	"github.com/pkg/errors"
	"google.golang.org/protobuf/types/descriptorpb"
)

var (
	// Well Known Types.
	excludedFiles = map[string]bool{
		"google/protobuf/timestamp.proto": true,
		"google/protobuf/wrappers.proto":  true,
	}

	// Avoid collisions with reserved keywords by appending a single underscore after the name.
	// This does not guarantee that collisions are avoided, but makes them less likely to
	// happen.
	reservedKeywords = map[string]bool{
		"module":   true,
		"exposing": true,
		"import":   true,
		"type":     true,
		"let":      true,
		"in":       true,
		"if":       true,
		"then":     true,
		"else":     true,
		"where":    true,
		"case":     true,
		"of":       true,
		"port":     true,
		"as":       true,
	}
)

type parameters struct {
	Debug            bool
	RemoveDeprecated bool
}

func parseParameters(input *string) (parameters, error) {
	var result parameters
	var err error

	if input == nil {
		return result, nil
	}

	for _, i := range strings.Split(*input, ",") {
		switch i {
		case "remove-deprecated":
			result.RemoveDeprecated = true
		case "debug":
			result.Debug = true
		default:
			err = fmt.Errorf("Unknown parameter: \"%s\"", i)
		}
	}

	return result, err
}

func main() {
	data, err := ioutil.ReadAll(os.Stdin)
	if err != nil {
		log.Fatalf("Could not read request from STDIN: %v", err)
	}

	req := &plugin.CodeGeneratorRequest{}

	err = proto.Unmarshal(data, req)
	if err != nil {
		log.Fatalf("Could not unmarshal request: %v", err)
	}

	parameters, err := parseParameters(req.Parameter)
	if err != nil {
		log.Fatalf("Failed to parse parameters: %v", err)
	}

	if parameters.Debug {
		// Remove useless source code data.
		for _, inFile := range req.GetProtoFile() {
			inFile.SourceCodeInfo = nil
		}

		log.Printf("Input data: %v", proto.MarshalTextString(req))
	}

	resp := &plugin.CodeGeneratorResponse{}

	for _, inFile := range req.GetProtoFile() {
		log.Printf("Processing file %s", inFile.GetName())
		// Well Known Types.
		if excludedFiles[inFile.GetName()] {
			log.Printf("Skipping well known type")
			continue
		}

		name := fileName(inFile.GetName())
		content, err := templateFile(inFile, parameters)
		if err != nil {
			log.Fatalf("Could not template file: %v", err)
		}

		resp.File = append(resp.File, &plugin.CodeGeneratorResponse_File{
			Name:    &name,
			Content: &content,
		})
	}

	data, err = proto.Marshal(resp)
	if err != nil {
		log.Fatalf("Could not marshal response: %v [%v]", err, resp)
	}

	_, err = os.Stdout.Write(data)
	if err != nil {
		log.Fatalf("Could not write response to STDOUT: %v", err)
	}
}

func hasMapEntries(inFile *descriptorpb.FileDescriptorProto) bool {
	for _, m := range inFile.GetMessageType() {
		if hasMapEntriesInMessage(m) {
			return true
		}
	}

	return false
}

func hasMapEntriesInMessage(inMessage *descriptorpb.DescriptorProto) bool {
	if inMessage.GetOptions().GetMapEntry() {
		return true
	}

	for _, m := range inMessage.GetNestedType() {
		if hasMapEntriesInMessage(m) {
			return true
		}
	}

	return false
}

func templateFile(inFile *descriptorpb.FileDescriptorProto, p parameters) (string, error) {
	t := template.New("t")

	t, err := elm.EnumCustomTypeTemplate(t)
	if err != nil {
		return "", errors.Wrap(err, "failed to parse enum custom type template")
	}

	t, err = elm.OneOfCustomTypeTemplate(t)
	if err != nil {
		return "", errors.Wrap(err, "failed to parse one-of custom type template")
	}

	t, err = elm.TypeAliasTemplate(t)
	if err != nil {
		return "", errors.Wrap(err, "failed to parse type alias template")
	}

	t, err = t.Parse(`
{{- define "nested-message" -}}
{{ template "type-alias" .TypeAlias }}
{{- range .OneOfCustomTypes }}


{{ template "oneof-custom-type" . }}
{{- end }}
{{- range .EnumCustomTypes }}


{{ template "enum-custom-type" . }}
{{- end }}
{{- range .NestedMessages }}


{{ template "nested-message" . }}
{{- end }}
{{- end -}}
`)

	if err != nil {
		return "", errors.Wrap(err, "failed to parse nested PB message template")
	}

	t, err = t.Parse(`module {{ .ModuleName }} exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: {{ .SourceFile }}

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE
{{- if .ImportDict }}
import Dict
{{- end }}
{{- range .AdditionalImports }}
import {{ . }} exposing (..)
{{ end }}


uselessDeclarationToPreventErrorDueToEmptyOutputFile = 42
{{- range .TopEnums }}


{{ template "enum-custom-type" . }}
{{- end }}
{{- range .Messages }}


{{ template "nested-message" . }}
{{- end }}
`)
	if err != nil {
		return "", err
	}

	messages, err := messages([]string{}, inFile.GetMessageType(), p)
	if err != nil {
		return "", err
	}

	buff := &bytes.Buffer{}
	if err = t.Execute(buff, struct {
		SourceFile        string
		ModuleName        string
		ImportDict        bool
		AdditionalImports []string
		TopEnums          []elm.EnumCustomType
		Messages          []pbMessage
	}{
		SourceFile:        inFile.GetName(),
		ModuleName:        moduleName(inFile.GetName()),
		ImportDict:        hasMapEntries(inFile),
		AdditionalImports: getAdditionalImports(inFile.GetDependency()),
		TopEnums:          enumsToCustomTypes([]string{}, inFile.GetEnumType(), p),
		Messages:          messages,
	}); err != nil {
		return "", err
	}

	return buff.String(), nil
}

type pbMessage struct {
	TypeAlias        elm.TypeAlias
	OneOfCustomTypes []elm.OneOfCustomType
	EnumCustomTypes  []elm.EnumCustomType
	NestedMessages   []pbMessage
}

func isDeprecated(options interface{}) bool {
	switch v := options.(type) {
	case *descriptorpb.MessageOptions:
		return v != nil && v.Deprecated != nil && *v.Deprecated
	case *descriptorpb.FieldOptions:
		return v != nil && v.Deprecated != nil && *v.Deprecated
	case *descriptorpb.EnumOptions:
		return v != nil && v.Deprecated != nil && *v.Deprecated
	case *descriptorpb.EnumValueOptions:
		return v != nil && v.Deprecated != nil && *v.Deprecated
	default:
		return false
	}
}

func enumsToCustomTypes(preface []string, enumPbs []*descriptorpb.EnumDescriptorProto, p parameters) []elm.EnumCustomType {
	var result []elm.EnumCustomType
	for _, enumPb := range enumPbs {
		if isDeprecated(enumPb.Options) && p.RemoveDeprecated {
			continue
		}

		var values []elm.EnumVariant
		for _, value := range enumPb.GetValue() {
			if isDeprecated(value.Options) && p.RemoveDeprecated {
				continue
			}

			values = append(values, elm.EnumVariant{
				Name:     elm.NestedVariantName(value.GetName(), preface),
				Number:   elm.ProtobufFieldNumber(value.GetNumber()),
				JSONName: elm.EnumVariantJSONName(value),
			})
		}

		enumType := elm.NestedType(enumPb.GetName(), preface)

		result = append(result, elm.EnumCustomType{
			Name:                   enumType,
			Decoder:                elm.DecoderName(enumType),
			Encoder:                elm.EncoderName(enumType),
			DefaultVariantVariable: elm.EnumDefaultVariantVariableName(enumPb.GetName(), preface),
			DefaultVariantValue:    values[0].Name,
			Variants:               values,
		})
	}

	return result
}

func oneOfsToCustomTypes(preface []string, messagePb *descriptorpb.DescriptorProto, p parameters) []elm.OneOfCustomType {
	var result []elm.OneOfCustomType

	if isDeprecated(messagePb.Options) && p.RemoveDeprecated {
		return result
	}

	for oneofIndex, oneOfPb := range messagePb.GetOneofDecl() {
		var variants []elm.OneOfVariant
		for _, inField := range messagePb.GetField() {
			if isDeprecated(inField.Options) && p.RemoveDeprecated {
				continue
			}

			if inField.OneofIndex == nil || inField.GetOneofIndex() != int32(oneofIndex) {
				continue
			}

			variants = append(variants, elm.OneOfVariant{
				Name:     elm.NestedVariantName(inField.GetName(), preface),
				JSONName: elm.OneOfVariantJSONName(inField),
				Type:     elm.BasicFieldType(inField),
				Decoder:  elm.BasicFieldDecoder(inField),
				Encoder:  elm.BasicFieldEncoder(inField),
			})
		}

		name := elm.NestedType(oneOfPb.GetName(), preface)
		result = append(result, elm.OneOfCustomType{
			Name:     name,
			Decoder:  elm.DecoderName(name),
			Encoder:  elm.EncoderName(name),
			Variants: variants,
		})
	}

	return result
}

func messages(preface []string, messagePbs []*descriptorpb.DescriptorProto, p parameters) ([]pbMessage, error) {
	var result []pbMessage
	for _, messagePb := range messagePbs {
		if isDeprecated(messagePb.Options) && p.RemoveDeprecated {
			continue
		}

		var newFields []elm.TypeAliasField
		for _, fieldPb := range messagePb.GetField() {
			if isDeprecated(fieldPb.Options) && p.RemoveDeprecated {
				continue
			}

			if fieldPb.OneofIndex != nil {
				continue
			}

			nested := getNestedType(fieldPb, messagePb)
			if nested != nil {
				newFields = append(newFields, elm.TypeAliasField{
					Name:    elm.FieldName(fieldPb.GetName()),
					Type:    elm.MapType(nested),
					Number:  elm.ProtobufFieldNumber(fieldPb.GetNumber()),
					Encoder: elm.MapEncoder(fieldPb, nested),
					Decoder: elm.MapDecoder(fieldPb, nested),
				})
			} else if isOptional(fieldPb) {
				newFields = append(newFields, elm.TypeAliasField{
					Name:    elm.FieldName(fieldPb.GetName()),
					Type:    elm.MaybeType(elm.BasicFieldType(fieldPb)),
					Number:  elm.ProtobufFieldNumber(fieldPb.GetNumber()),
					Encoder: elm.MaybeEncoder(fieldPb),
					Decoder: elm.MaybeDecoder(fieldPb),
				})
			} else if isRepeated(fieldPb) {
				newFields = append(newFields, elm.TypeAliasField{
					Name:    elm.FieldName(fieldPb.GetName()),
					Type:    elm.ListType(elm.BasicFieldType(fieldPb)),
					Number:  elm.ProtobufFieldNumber(fieldPb.GetNumber()),
					Encoder: elm.ListEncoder(fieldPb),
					Decoder: elm.ListDecoder(fieldPb),
				})
			} else {
				newFields = append(newFields, elm.TypeAliasField{
					Name:    elm.FieldName(fieldPb.GetName()),
					Type:    elm.BasicFieldType(fieldPb),
					Number:  elm.ProtobufFieldNumber(fieldPb.GetNumber()),
					Encoder: elm.RequiredFieldEncoder(fieldPb),
					Decoder: elm.RequiredFieldDecoder(fieldPb),
				})
			}
		}

		for _, oneOfPb := range messagePb.GetOneofDecl() {
			newFields = append(newFields, elm.TypeAliasField{
				Name:    elm.FieldName(oneOfPb.GetName()),
				Type:    elm.OneOfType(oneOfPb.GetName()),
				Encoder: elm.OneOfEncoder(oneOfPb),
				Decoder: elm.OneOfDecoder(oneOfPb),
			})
		}

		newPreface := append([]string{messagePb.GetName()}, preface...)
		nestedMessages, err := messages(newPreface, messagePb.GetNestedType(), p)
		if err != nil {
			return nil, err
		}

		name := elm.NestedType(messagePb.GetName(), preface)
		result = append(result, pbMessage{
			TypeAlias: elm.TypeAlias{
				Name:    name,
				Decoder: elm.DecoderName(name),
				Encoder: elm.EncoderName(name),
				Fields:  newFields,
			},
			OneOfCustomTypes: oneOfsToCustomTypes([]string{}, messagePb, p),
			EnumCustomTypes:  enumsToCustomTypes(newPreface, messagePb.GetEnumType(), p),
			NestedMessages:   nestedMessages,
		})
	}

	return result, nil
}

func isOptional(inField *descriptorpb.FieldDescriptorProto) bool {
	return inField.GetLabel() == descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL &&
		inField.GetType() == descriptorpb.FieldDescriptorProto_TYPE_MESSAGE
}

func isRepeated(inField *descriptorpb.FieldDescriptorProto) bool {
	return inField.GetLabel() == descriptorpb.FieldDescriptorProto_LABEL_REPEATED
}

func getNestedType(inField *descriptorpb.FieldDescriptorProto, inMessage *descriptorpb.DescriptorProto) *descriptorpb.DescriptorProto {

	// TODO: Is there a better way?  Convert to a function with descriptive name.
	fullyQualifiedTypeName := inField.GetTypeName()
	splitName := strings.Split(fullyQualifiedTypeName, ".")
	localTypeName := splitName[len(splitName)-1]

	for _, nested := range inMessage.GetNestedType() {
		if nested.GetName() == localTypeName && nested.GetOptions().GetMapEntry() {
			return nested
		}
	}

	return nil
}

func fileName(inFilePath string) string {
	inFileDir, inFileName := filepath.Split(inFilePath)

	trimmed := strings.TrimSuffix(inFileName, ".proto")
	shortFileName := firstUpper(trimmed)

	fullFileName := ""
	for _, segment := range strings.Split(inFileDir, "/") {
		if segment == "" {
			continue
		}

		fullFileName += firstUpper(segment) + "/"
	}

	return fullFileName + shortFileName + ".elm"
}

func moduleName(inFilePath string) string {
	inFileDir, inFileName := filepath.Split(inFilePath)

	trimmed := strings.TrimSuffix(inFileName, ".proto")
	shortModuleName := firstUpper(trimmed)

	fullModuleName := ""
	for _, segment := range strings.Split(inFileDir, "/") {
		if segment == "" {
			continue
		}

		fullModuleName += firstUpper(segment) + "."
	}

	return fullModuleName + shortModuleName
}

func getAdditionalImports(dependencies []string) []string {
	var additions []string
	for _, d := range dependencies {
		if excludedFiles[d] {
			continue
		}

		fullModuleName := ""
		for _, segment := range strings.Split(strings.TrimSuffix(d, ".proto"), "/") {
			if segment == "" {
				continue
			}
			fullModuleName += firstUpper(segment) + "."
		}

		additions = append(additions, strings.TrimSuffix(fullModuleName, "."))
	}
	return additions
}

func firstUpper(in string) string {
	if len(in) < 2 {
		return strings.ToUpper(in)
	}

	return strings.ToUpper(string(in[0])) + string(in[1:])
}
