#!/bin/sh

set -ex

readonly ROOT="$(dirname "$0")"

(
  cd ${ROOT}/proto

  readonly PROTOC="../../../protoc/bin/protoc"
  ${PROTOC} --elm_out=../elm ./*.proto
)

(
  cd ${ROOT}/elm

  elm-package install -y

  elm-test ./Main.elm
)
