#!/bin/sh

set -ex

readonly ROOT="$(dirname "$0")"

(
  cd $ROOT/proto

  protoc --elm_out=../elm ./*.proto
)

(
  cd $ROOT/elm

  elm-package install -y
  elm-make --yes --output raw-test.js ./Test.elm
  elm-test TestRunner.elm
)
