#!/bin/sh

set -ex

readonly ROOT="$(dirname "$0")"

(
  cd $ROOT/proto

  protoc --csharp_out=../csharp --python_out=../python --java_out=../java --elm_out=../elm ./**/*.proto ./*.proto
)

(
  cd $ROOT/elm

  elm-package install -y

  elm-test ./Main.elm
)
