module File2 exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: file2.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias File2Message =
    { field : Bool -- 1
    }
type File2MessageMessage = File2MessageMessage File2Message


file2MessageDecoder : JD.Decoder File2Message
file2MessageDecoder =
    JD.lazy <| \_ -> decode File2Message
        |> required "field" JD.bool False


file2MessageEncoder : File2Message -> JE.Value
file2MessageEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "field" JE.bool False v.field)
        ]
