#!/bin/bash

set -euo pipefail
set -x

readonly ROOT="$(git rev-parse --show-toplevel)"
readonly TEST_PLUGIN="${ROOT}/elm-test-project/elm-protobuf-test"

cd "${ROOT}"
GO111MODULE=on go build -o "${TEST_PLUGIN}" ./cmd/protoc-gen-elm
