#!/bin/bash

set -euo pipefail
set -x

readonly ROOT="$(git rev-parse --show-toplevel)"
readonly TEST_PLUGIN="${ROOT}/elm-project/elm-protobuf-test"

if [[ ! -f "${TEST_PLUGIN}" ]]; then
    echo "compiled test plugin required"
    exit 1
fi

protoc \
    --proto_path="${ROOT}/elm-project/tests/proto" \
    --elm_out="${ROOT}/elm-project/tests" \
    --plugin=protoc-gen-elm="${TEST_PLUGIN}" \
    "${ROOT}"/elm-project/tests/proto/*.proto

cd "${ROOT}/elm-project"
elm-test
