#!/bin/bash

set -euo pipefail
set -x

readonly ROOT="$(git rev-parse --show-toplevel)"
readonly TEST_PLUGIN="${ROOT}/elm-test-project/elm-protobuf-test"

if [[ ! -f "${TEST_PLUGIN}" ]]; then
    echo "compiled test plugin required"
    exit 1
fi

protoc \
    --proto_path="${ROOT}/elm-test-project/tests/proto" \
    --elm_out="${ROOT}/elm-test-project/src" \
    --plugin=protoc-gen-elm="${TEST_PLUGIN}" \
    "${ROOT}"/elm-test-project/tests/proto/*.proto

cd "${ROOT}/elm-test-project"
pwd
elm-test
